### ISSUE TITLE
Semantic versioning in dependencies

### ISSUE THREAD

**Issue by braian125** [yajuve/temo-chat-ionic#1]
https://github.com/yajuve/temo-chat-ionic/blob/2fdf3edf988e3e9c935f102e9084199754056843/package.json#L3

You must use semantic versioning here, otherwise it will be an error and you will not be able to install the dependencies, please use "version": "1.0.0" instead "version": "1.0"

**Comment by yajuve** [comment]
Fixed [102fc74](https://github.com/yajuve/temo-chat-ionic/commit/a18e9cba98f5854c6ddabee603628569b89cdabf)
Thanks for your report
